"""yeni db

Revision ID: 1c15b64aff10
Revises: 653f9250f293
Create Date: 2025-10-27 22:41:53.043504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c15b64aff10'
down_revision = '653f9250f293'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kiralama', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kiralama_form_no', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kiralama', schema=None) as batch_op:
        batch_op.drop_column('kiralama_form_no')

    # ### end Alembic commands ###
