"""hesaplama

Revision ID: 2d0b6906d5ed
Revises: 1c15b64aff10
Create Date: 2025-10-28 00:45:34.251815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d0b6906d5ed'
down_revision = '1c15b64aff10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kiralama', schema=None) as batch_op:
        batch_op.alter_column('kiralama_form_no',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kiralama', schema=None) as batch_op:
        batch_op.alter_column('kiralama_form_no',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
