"""Ekipman yükseklik ve kapasiteyi integer yaptı

Revision ID: c6704ec1bd80
Revises: 
Create Date: 2025-10-31 11:04:52.267266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6704ec1bd80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ekipman',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kod', sa.String(length=100), nullable=False),
    sa.Column('yakit', sa.String(length=50), nullable=False),
    sa.Column('tipi', sa.String(length=100), nullable=False),
    sa.Column('marka', sa.String(length=100), nullable=False),
    sa.Column('seri_no', sa.String(length=100), nullable=False),
    sa.Column('calisma_yuksekligi', sa.Integer(), nullable=False),
    sa.Column('kaldirma_kapasitesi', sa.Integer(), nullable=False),
    sa.Column('uretim_tarihi', sa.String(length=100), nullable=False),
    sa.Column('calisma_durumu', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ekipman', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ekipman_kod'), ['kod'], unique=True)
        batch_op.create_index(batch_op.f('ix_ekipman_seri_no'), ['seri_no'], unique=True)

    op.create_table('musteri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firma_adi', sa.String(length=150), nullable=False),
    sa.Column('yetkili_adi', sa.String(length=100), nullable=False),
    sa.Column('iletisim_bilgileri', sa.String(length=200), nullable=False),
    sa.Column('vergi_dairesi', sa.String(length=100), nullable=False),
    sa.Column('vergi_no', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vergi_no')
    )
    op.create_table('kiralama',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kiralama_form_no', sa.String(length=100), nullable=True),
    sa.Column('musteri_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['musteri_id'], ['musteri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kiralama_kalemi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kiralama_id', sa.Integer(), nullable=False),
    sa.Column('ekipman_id', sa.Integer(), nullable=False),
    sa.Column('kiralama_baslangıcı', sa.String(length=50), nullable=False),
    sa.Column('kiralama_bitis', sa.String(length=50), nullable=False),
    sa.Column('kiralama_brm_fiyat', sa.String(length=50), nullable=False),
    sa.Column('nakliye_fiyat', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['ekipman_id'], ['ekipman.id'], ),
    sa.ForeignKeyConstraint(['kiralama_id'], ['kiralama.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kiralama_kalemi')
    op.drop_table('kiralama')
    op.drop_table('musteri')
    with op.batch_alter_table('ekipman', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ekipman_seri_no'))
        batch_op.drop_index(batch_op.f('ix_ekipman_kod'))

    op.drop_table('ekipman')
    # ### end Alembic commands ###
